//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azutka_Kelime_Bulucu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KelimeGönderiktenSonraDur {
            get {
                return ((string)(this["KelimeGönderiktenSonraDur"]));
            }
            set {
                this["KelimeGönderiktenSonraDur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HarfGönderdiktenSonraDur {
            get {
                return ((string)(this["HarfGönderdiktenSonraDur"]));
            }
            set {
                this["HarfGönderdiktenSonraDur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CheckKelimeG {
            get {
                return ((string)(this["CheckKelimeG"]));
            }
            set {
                this["CheckKelimeG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CheckHarfG {
            get {
                return ((string)(this["CheckHarfG"]));
            }
            set {
                this["CheckHarfG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BasılacakTus {
            get {
                return ((int)(this["BasılacakTus"]));
            }
            set {
                this["BasılacakTus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LisansKey {
            get {
                return ((string)(this["LisansKey"]));
            }
            set {
                this["LisansKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Kullaniciİsmi {
            get {
                return ((string)(this["Kullaniciİsmi"]));
            }
            set {
                this["Kullaniciİsmi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KullaniciİsmiBool {
            get {
                return ((int)(this["KullaniciİsmiBool"]));
            }
            set {
                this["KullaniciİsmiBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GirişDurumu {
            get {
                return ((int)(this["GirişDurumu"]));
            }
            set {
                this["GirişDurumu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProgramKodu {
            get {
                return ((string)(this["ProgramKodu"]));
            }
            set {
                this["ProgramKodu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailBirikimi {
            get {
                return ((string)(this["MailBirikimi"]));
            }
            set {
                this["MailBirikimi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(A)(B)(C)(Ç)(D)(E)(F)(G)(Ğ)(H)(I)(İ)(J)(K)(L)(M)(N)(O)(Ö)(P)(R)(S)(Ş)(T)(U)(Ü)(V)" +
            "(Y)(Z)")]
        public string Jokerler {
            get {
                return ((string)(this["Jokerler"]));
            }
            set {
                this["Jokerler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KGSDBool {
            get {
                return ((bool)(this["KGSDBool"]));
            }
            set {
                this["KGSDBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HGSDBool {
            get {
                return ((bool)(this["HGSDBool"]));
            }
            set {
                this["HGSDBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(TK)(12)(11)(10)(9)(8)(7)(6)(5)(4)(3)")]
        public string ÜretilecekKelimeler {
            get {
                return ((string)(this["ÜretilecekKelimeler"]));
            }
            set {
                this["ÜretilecekKelimeler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KelimeGöndericiBool {
            get {
                return ((bool)(this["KelimeGöndericiBool"]));
            }
            set {
                this["KelimeGöndericiBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JokerHarfBool {
            get {
                return ((bool)(this["JokerHarfBool"]));
            }
            set {
                this["JokerHarfBool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JokerAyarlar {
            get {
                return ((bool)(this["JokerAyarlar"]));
            }
            set {
                this["JokerAyarlar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<A1A><B3B><C4C><Ç4Ç><D3D><E1E><F7F><G5G><Ğ8Ğ><H5H><I2I><İ1İ><J10J><K1K><L1L><M2M>" +
            "<N1N><O2O><Ö7Ö><P5P><R1R><S2S><Ş4Ş><T1T><U2U><Ü3Ü><V7V><Y3Y><Z4Z>")]
        public string HarfPuan {
            get {
                return ((string)(this["HarfPuan"]));
            }
            set {
                this["HarfPuan"] = value;
            }
        }
    }
}
